import { Geist, Geist_Mono } from "next/font/google";
import "../css/globals.css";
import Sidebar from "@/layouts/navbar/Sidebar";
import { ThemProvider } from "@/components/themProvider/ThemProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex gap-10 h-screen px-10 max-w-s `}>
        <ThemProvider attribute="class" defaultTheme="light" themes={["light", "dark"]} disableTransitionOnChange>
          <Sidebar className={"w-3/12"}></Sidebar>
          <div className=" w-9/12 ">{children}</div>
        </ThemProvider>
      </body>
    </html>
  );
}
